participants:
  - el_type: geth
    cl_type: lighthouse
    #cl_image: my-lighthouse:randao-fork
    validator_count: 128
    
  - el_type: geth
    cl_type: lighthouse
    #cl_image: my-lighthouse:randao-fork
    validator_count: 128

  - el_type: geth
    cl_type: lighthouse
    #cl_image: my-lighthouse:randao-fork
    validator_count: 128

  - el_type: geth
    cl_type: lighthouse
    #cl_image: my-lighthouse:randao-fork
    validator_count: 128

network_params:
    seconds_per_slot: 6
    electra_fork_epoch: 0
    preset: "mainnet"

# wait for chain finalisation (13 min approx.)
wait_for_finalization: true  # This will pause until chain is finalized
